### ISSUE TITLE
Description doesn't inherit code blocks when using upstream_descriptions.

### ISSUE THREAD

**Issue by diegodewilde** [dbt-labs/dbt-codegen#111]
### Describe the bug
When using the `generate_model_yaml` functionality with `upstream_descriptions` it seems that the generated yaml file doesn't use the **exact** yaml description from upstream. Instead it uses the "compiled" description. This is a problem when using code blocks and goes directly against the reason to use code blocks. 

### Steps to reproduce
_You can skip A by using the attached zip file which contains the necessary files._ 
[reproduce-files.zip](https://github.com/dbt-labs/dbt-codegen/files/10382402/reproduce-files.zip)

#### A. We need the following steps (1->3) to setup a demo environment.
1. Create a model file `dummy_model.sql` with the following content:
```sql
select
    'foo' as first_column
```
2. Create a yaml file `dummy_model.yml` with the following content: 
```yaml
version: 2

models:
  - name: dummy_model
    description: "" # Let's keep this line out of scope, as you probably never want to use upstream descriptions here.
    columns:
      - name: first_column
        description: "{{ doc('dummy_model__first_column') }}"
```
3. Create a md file `dummy_model.md` with the following content: 
```jinja2
{% docs dummy_model__first_column %}

The description about the `first column` model! 

{% enddocs %}
```
4. Create a second model file `second_dummy_model.sql` with the following content:
```sql
select
    *
from {{ ref('dummy_model') }}
```

#### B. Now we can execute the following commands to generate the model yaml (using upstream descriptions).
```bash
dbt compile
dbt run-operation generate_model_yaml --args '{"model_names": ["second_dummy_model"], "upstream_descriptions": true}'
```

### Expected results
The generated yaml file should contain the same column descriptions as the upstream model. In this case, this would need to be `"{{ doc('dummy_model__first_column') }}"`.
Full expected result would be: 
```yaml
version: 2

models:
  - name: second_dummy_model
    description: ""
    columns:
      - name: first_column
        description: "{{ doc('dummy_model__first_column') }}"

```

### Actual results
However, the result is the "compiled" description as you can see below:
```yaml
version: 2

models:
  - name: second_dummy_model
    description: ""
    columns:
      - name: first_column
        description: "The description about the `first column` model!"

```

### Screenshots and log output
Not required.

### System information
Not required.

### Are you interested in contributing the fix?
Certainly, but I can't find a way to get the original description. Couldn't find it in the used graph object myself, so hopefully someone can lend a hand here! Asked it in the `#advice-dbt-for-power-users` channel on Slack as well with [this post](https://getdbt.slack.com/archives/C2JRRQDTL/p1673273656580929).
