### ISSUE TITLE
Store artifacts in Circle CI to aid troubleshooting

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-codegen#212]
### Describe the feature

Configure storage of `logs` and `target` directories within [`.circleci/config.yml`](https://github.com/dbt-labs/dbt-codegen/blob/696c9f01758d727f9c1a360fcbe5af7b5ab7fa1e/.circleci/config.yml) to aid in troubleshooting.

Add something like this to each run step:

```yaml
      - store_artifacts:
          path: integration_tests/logs

      - store_artifacts:
          path: integration_tests/target
```

Same as in [`config.yml` in `dbt-utils`](https://github.com/dbt-labs/dbt-utils/blob/f13a392ed3959a98385197a2d46622c1a35327d6/.circleci/config.yml).

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.
