### ISSUE TITLE
generate_model_yaml function is writing columns description only for table materializations

### ISSUE THREAD

**Issue by daviibf** [dbt-labs/dbt-codegen#247]
### Describe the bug
For non-table materialized models, the `generate_model_yaml` method does not generate columns description.

### Steps to reproduce
1. Write an intermediary model of type `materialized_view`:

```yaml
-- models/int_orders.sql

{{ config(
    materialized='view'  -- Specifies that this model should be materialized as a view
) }}

WITH orders AS (
    SELECT
        customer_id,
        order_id,
        order_date,
        order_status,
        total_amount
    FROM {{ ref('raw_orders') }}  -- Reference a raw source table
)

SELECT *
FROM orders
```

2. Then, execute `generate_model_yaml` for this model.
```yaml
version: 2

models:
  - name: int_orders
    description: ""
    columns:
      - name: customer_id
        data_type: uuid
        description: ""

      - name: order_id
        data_type: uuid
        description: ""

      - name: order_date
        data_type: timestamp
        description: ""

      - name: order_status
        data_type: character varying
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""
```

### Actual results
```yaml
version: 2

models:
  - name: int_orders
    description: ""
    columns:
```

### System information
**The contents of your `packages.yml` file:**
```yaml
packages:
  - package: calogica/dbt_expectations
    version: [">=0.1.0", "<1.0.0"]
  - package: dbt-labs/audit_helper
    version: [">=0.3.0", "<1.0.0"]
  # - package: jpmmcneill/dbt_graph_theory
  #   version: [">=0.2.0", "<1.0.0"]
  - package: calogica/dbt_date
    version: [">=0.1.0", "<1.0.0"]
  - package: dbt-labs/logging
    version: [">=0.1.0", "<1.0.0"]
  - package: dbt-labs/dbt_utils
    version: [">=1.1.0", "<2.0.0"]
  - package: elementary-data/elementary
    version: 0.16.1
  - package: dbt-labs/codegen
    version: 0.13.1

```

**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.1
  - latest:    1.9.1 - Up to date!

Plugins:
  - postgres: 1.9.0 - Up to date!
```

**The operating system you're using:**
Apple M3 Pro

**The output of `python --version`:**
Python 3.11.9

**Comment by henry-yu-gce** [comment]
Wanted to chime in and say that I'm also experiencing this issue using BigQuery and materialized as anything but table (in this schema or any dependent schema)

**Comment by gabeschenz** [comment]
+1 on this defect.  I am seeing the same with Snowflake, using the dbt cloud cli.

```yaml
packages:
  - package: dbt-labs/codegen
    version: 0.13.1
  - package: dbt-labs/dbt_utils
    version: 1.3.0
```

```shell
❯ dbt --version
dbt Cloud CLI - 0.38.32 (c75d8c4750469a2ce02e61939c29dc753dec1b94 2025-03-12T21:03:52Z)
```
