### ISSUE TITLE
Generate_model_yaml doesn't recognize nested BigQuery columns

### ISSUE THREAD

**Issue by RBozydar** [dbt-labs/dbt-codegen#27]
### Describe the bug
generate_model_yaml doesn't recognize nested bigquery columns

### Steps to reproduce
Create a model with nested columns, either through STRUCT() or ARRAY(), for example:
```
STRUCT(
   source,
   medium,
   source_medium
) analytics
```
### Expected results
The macro should print out the nested columns as well, now it prints out only the "main" column/field.
With the example above we should get
source, medium, source_medium and analytics as columns in the yaml output

### Actual results
The macro prints out only the "main" column/field which is analytics

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.5.0
  - package: fishtown-analytics/codegen
    version: 0.1.0
```
**Which database are you using dbt with?**
- [x] bigquery

**The output of `dbt --version`:**
```
installed version: 0.17.1
   latest version: 0.17.1
```

**The operating system you're using:**
Ubuntu 18.04
**The output of `python --version`:**
Python 3.8.1

### Are you interested in contributing the fix?
I would love to, unfortunately my knowledge of Jinja isn't sufficient so I'd appreciate some pointers
