### ISSUE TITLE
Option for generate_model_yaml to add docs blocks references

### ISSUE THREAD

**Issue by oscarlukersmithsc** [dbt-labs/dbt-codegen#48]
### Describe the feature
It would be useful to have an optional parameter in generate_model_yaml to also generate relevant docs blocks references. It will should default to false (not generating the docs) but writing something such as 
`{{ codegen.generate_model_yaml('data_user', docs_blocks = true) }}`
Should generate something like 

```
version: 2

models:
  - name: data_user
    description: ""
    columns:
      - name: user_hk
        description: 'docs{{ "user_hk" }}'

      - name: user_id
        description: 'docs{{ "user_id" }}'

      - name: create_date
        description: 'docs{{ "create_date" }}'

      - name: email_address_text
        description: 'docs{{ "email_address_text" }}'
```

We are only using docs blocks instead of just strings when documenting.

### Describe alternatives you've considered
We are currently using an adapted version of the codegen macro in our dbt project to achieve the same thing, previously we were manually copying and pasting :P

### Who will this benefit?
Anyone who uses docs blocks as the default documentation method in their project.

### Are you interested in contributing this feature?
Yes, I have a working macro in my dbt project.
