### ISSUE TITLE
Generate Model Yaml not seeing columns, just model name.

### ISSUE THREAD

**Issue by pkanter** [dbt-labs/dbt-codegen#69]
Apologies if this is not the correct place to ask this question.

When I run generate_model_yaml, the code that is returned doesn't have the column names, just the model name.

For example, running this:
```
{{ codegen.generate_model_yaml(
    model_name='fct_shopify_variant_metafield'
) }}
```
Produces this:
```
models:
  - name: fct_shopify_variant_metafield
    description: ""
    columns:
```
I must be doing something wrong, but cannot future out what it is.  Any assistance would be appreciated.
