### ISSUE TITLE
Generate model yaml not importing descriptions from upstream

### ISSUE THREAD

**Issue by tamireinhorn** [dbt-labs/dbt-codegen#70]
### Describe the bug

As per the title, once I run the command, the YAML generated has all the columns in lower case but doesn't get the descriptions from upstream.

### Steps to reproduce

It seems this has to do with it being case insensitive somehow. My upstream model has a column called 'currentSite', and the YAML generated creates it as 'currentsite' without any description. 
This is done on DBT Cloud.

### System information
```
packages:
  - package: dbt-labs/codegen
    version: 0.7.0
  - package: dbt-labs/dbt_utils
    version: 0.8.6
  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.0
```

### Are you interested in contributing the fix?
If I could, but I've never written something to a DBT package, so I'm not sure I can help.
