### ISSUE TITLE
`generate_model_yaml macro` to take original yaml file as an additional argument

### ISSUE THREAD

**Issue by charlespicowski** [dbt-labs/dbt-codegen#73]
Looking at the [generate_model_yaml](https://github.com/dbt-labs/dbt-codegen/tree/0.7.0/macros/generate_model_yaml.sql) macro, I can see that it takes the following arguments:

- `model_name`
- `upstream_descriptions`

As I understand it, running

`dbt run-operation generate_model_yaml --args '{"model_name": "dim_customer"}'`

will produce a yaml similar to the following

```
version: 2

models:
  - name: dim_customer
    description: ""
    columns:
      - name: dim_customer_id
        description: ""

      - name: customer_id
        description: ""

      - name: customer_first_name
        description: ""

...
```

But what if there is an already existing `yml` file for `dim_customers` such as...

```
...
  - name: dim_customer
    description: ""
    columns:
      - name: dim_customer_id
        description: "this is my description"
        meta:
           - something_else:
        tests_and_other_things...:
...
```

Is it possible we can take these original descriptions, tests and meta things too for the new output produced by the `generate_model_yaml` macro?

**Why someone would want this**: Most of the time you are not in fact generating a model `yaml` from scratch, there is an already existing one, and you have made changes to it. It's really a quality of life improvement, but it would greatly improve one's workflow and make it easier to keep documentation best practices.
