### ISSUE TITLE
generate_source on Snowflake doesn't generate any table names

### ISSUE THREAD

**Issue by jaredx435k2d0** [dbt-labs/dbt-codegen#89]
### Describe the bug

generate_source on Snowflake doesn't generate any table names (or columns). I'm not seeing any errors anywhere. It simply doesn't finish outputting the yml.

This only happens for some schemas in my source DB. I don't see a pattern in why it happens in some but not others.

### Steps to reproduce

I executed
`dbt run-operation generate_source --args '{"schema_name": "my_actual_schema_name", "database_name": "my_actual_database_name", "generate_columns": "True"}'`

### Expected results

```
version: 2

sources:
  - name: [my_actual_source_name]
    database: my_actual_database_name
    tables:
      - name: accounts
        description: ""
        columns:
          - name: id
            description: ""
          - name: country_id
            description: ""

      - name: products
        description: ""
        columns:
          - name: id
            description: ""
          - name: name
            description: ""
          - name: record_type
            description: ""
```

### Actual results

```
version: 2

sources:
  - name: [my_actual_source_name]
    database: my_actual_database_name
    tables:
```

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt --version
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - snowflake: 1.3.0 - Up to date!
```

**The operating system you're using:**
macOS 12.6.1 (21G217)

**The output of `python --version`:**
3.9.15
